# Generated by Django 6.0.6 on 2026-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
