# Generated by Django 6.0.6 on 2026-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservationmember_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='leader_name',
            field=models.CharField(default='Belum Diisi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='leader_phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationmember',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
