# Generated by Django 6.0.6 on 2026-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_leader_name_reservation_leader_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='leader_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='leader_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
