# Generated by Django 6.0.6 on 2026-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_leader_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmember',
            name='identity_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reservation_ktp/'),
        ),
    ]
