# Generated by Django 6.0.6 on 2026-06-27 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hiking_date', models.DateField(unique=True)),
                ('quota', models.PositiveIntegerField()),
                ('remaining_quota', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weather_status', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weather_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['hiking_date'],
            },
        ),
    ]
