# Generated by Django 6.0.6 on 2026-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
