# Generated by Django 6.0.6 on 2026-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_address_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OFFICER', 'Officer'), ('HIKER', 'Hiker')], default='HIKER', max_length=20),
        ),
    ]
