# Generated by Django 6.0.6 on 2026-06-27 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_out_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'checkins',
            },
        ),
    ]
